services:
  db:
    container_name: db
    image: postgres:17
    networks:
      - main
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    networks:
      - main
    volumes:
      - .:/code/
    restart: always
    depends_on:
      - db
volumes:
  postgres_db:
networks:
  main: